### ISSUE TITLE
Crash when clicking on job

### ISSUE THREAD

**Issue by KuroNeko87** [Globox1997/JobsAddon#11]
Minecraft crashes when selecting a job in the jobs tab. Mod version: 1.0.8

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
Time: 2023-02-07 07:03:34
Description: Rendering screen
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7950(net.minecraft.class_1657, net.minecraft.class_1836)" because "$$0" is null
	at net.minecraft.class_437.method_25408(class_437.java:181)
	at net.minecraft.class_437.constant$dmm000$renderTooltipFromComponentsColorTwoMixin(class_437.java:770)
	at net.minecraft.class_437.method_32633(class_437.java:231)
	at net.minecraft.class_437.method_25417(class_437.java:193)
	at io.github.cottonmc.cotton.gui.widget.WWidget.renderTooltip(WWidget.java:356)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.method_25394(CottonClientScreen.java:146)
	at net.jobsaddon.gui.JobsScreen.method_25394(JobsScreen.java:46)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

Mods list:
	- additionz 1.1.3
	- advanced_runtime_resource_pack 0.6.4
	- adventurez 1.4.17
	- amecsapi 1.3.6+mc22w17a via backslot
	- autotag 2.0.0+1.19 via autotag-convention
	- autotag-convention 2.0.0+1.19
	- backslot 1.2.11
	- backslotaddon 1.0.10
	- blue_endless_jankson 1.2.1 via owo
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- dehydration 1.3.3
	- dragonloot 1.1.2
	- dualwielding 1.1.2
	- dynamicfps 2.2.0
	- earlystage 1.0.5
	- environmentz 1.3.5
	- eventmod 1.0.5
	- fabric-api 0.73.2+1.19.2
	- fabricloader 0.14.14
	- fabricshieldlib 1.6.1-1.19
	- ferritecore 5.0.3
	- fiber 0.23.0-2 via patchouli
	- fireplacemode 1.0.5
	- forgeconfigapiport 4.2.10
	- herdspanic 1.0.6
	- indium 1.0.9+mc1.19.2
	- inmis 2.7.1-1.19
	- inmisaddon 1.0.3
	- io_github_douira_glsl-transformer 2.0.0-pre9 via iris
	- iris 1.5.2
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- jobsaddon 1.0.8
	- lazydfu 0.1.3
	- levelz 1.4.4
	- libgui 6.0.1+1.19 via levelz
	- libninepatch 1.1.0 via libgui
	- lithium 0.10.4
	- medievalweapons 1.4.2
	- minecraft 1.19.2
	- mm 2.3 via fabricshieldlib
	- mobz 3.3.5
	- modmenu 4.1.2
	- nameplate 1.0.10
	- numismatic-overhaul 0.2.8+1.19
	- numismaticclaim 1.0.4
	- omega-config 1.2.3-1.18.1 via inmis
	- openpartiesandclaims 0.16.6
	- owo 0.9.3+1.19
	- patchouli 1.19.2-77-FABRIC
	- patchoulibutton 1.0.2
	- reach-entity-attributes 2.3.0 via medievalweapons
	- reciperemover 1.0.5
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- revive 1.0.5
	- rotten 1.4.7
	- rpgdifficulty 1.3.5
	- satin 1.8.0 via environmentz
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.16+mc1.19.2-build.90
	- stacc 1.3.3 via numismatic-overhaul
	- starlight 1.1.1+fabric.ae22326
	- talkbubbles 1.0.4
	- tiered 1.2.1
[latest.log](https://github.com/Globox1997/JobsAddon/files/10674391/latest.log)

	- tooltiprareness 1.0.7
	- villagerfix 1.0.3
	- villagerquests 1.0.7
	- voidz 1.0.9

**Comment by Globox1997** [comment]
can you try this without tooltip rareness mod?

**Comment by Globox1997** [comment]
Please open this at the tooltip rareness repository.
